# Generated by Django 3.2.16 on 2024-05-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_birthday_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='comment',
        ),
    ]
