# Generated by Django 3.2.16 on 2024-05-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0007_congratulation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contest',
        ),
    ]
